#!/bin/bash

SESSION_NAME="gift"

# Check if session exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
  echo "Session $SESSION_NAME already exists. Attaching..."
  tmux attach -t $SESSION_NAME
  exit 0
fi

# Session does not exist, create it
echo "Creating new tmux session: $SESSION_NAME"

# cd /home/cofi/Documents/projects/vroom/frontend/vroom
#
# code .


cd /home/hy/Documents/projects/fullStack/gift/


tmux new-session -d -s $SESSION_NAME

tmux rename-window -t $SESSION_NAME:1 'vi'
tmux send-keys -t $SESSION_NAME:vi 'source env/bin/activate' C-m
tmux send-keys -t $SESSION_NAME:vi 'cd gift_be' C-m
tmux send-keys -t $SESSION_NAME:vi 'nvim .' C-m

tmux new-window -t $SESSION_NAME -n 'dj'
tmux send-keys -t $SESSION_NAME:dj 'source env/bin/activate' C-m
tmux send-keys -t $SESSION_NAME:dj 'cd gift_be' C-m
tmux send-keys -t $SESSION_NAME:dj 'run 0.0.0.0:8009' C-m

tmux new-window -t $SESSION_NAME -n 'vi_fe'
tmux send-keys -t $SESSION_NAME:vi_fe 'cd gift_customer' C-m
tmux send-keys -t $SESSION_NAME:vi_fe 'nvim .' C-m



tmux new-window -t $SESSION_NAME -n 'expo'
tmux send-keys -t $SESSION_NAME:expo 'cd gift_customer' C-m
tmux send-keys -t $SESSION_NAME:expo 'bun start' C-m

# Select the 'vi' window on attach
tmux select-window -t $SESSION_NAME:vi

# Attach to the session
tmux attach -t $SESSION_NAME
